### PR TITLE
Optimize the Dockerfile to separate the builder from the runner. Include java 11 support. Refine the changelog template

### LINKED ISSUE #9: feature: Refine the Dockerfile to avoid including dependencies in the image
# Feature Request

**Describe the Feature Request**
Currently the Dockerfile execute maven and the image contains the dependencies increasing its size.

**Is your feature request related to a problem? Please describe**
The image generated includes all the maven dependencies increasing the size and this could be avoided.

**Describe Preferred Solution**
Build the image with the dependencies and include in the image only the final artefact executed in a clean java environment.

**Additional Context**
Check [this blog with best practices in the docker image generation with maven](https://blog.docker.com/2019/07/intro-guide-to-dockerfile-best-practices/)

### PR DESCRIPTION
**Pull request by carloscaverobarca**
## Proposed Changes

  - Remove the changelog from PluginManagement section
  - Modify the mustache template to keep the changes clearer
  - Optimize the Dockerfile to separate the builder from the runner
  - Add java 11 and jetty 9.4

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests
- [x] Build locally
- [x] Code format / lint
- [ ] Docs have been reviewed and added

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Currently the docker image is generated using the builder_image script. 
Fixes #9 

## What is the new behavior?

- Lighter docker image
- Changelog clearer and readable for humans
- Automatic docker image generation in Docker Hub

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Build the docker image before accepting the PR.

### CODE REVIEW

**Comment by mariorguezari** [comment]
This repo is getting better and better.
About Java 11 support, 
does the continuous integration pipeline compile in Java 11?

**Comment by carloscaverobarca** [comment]
Yes it compiles in java 11. We need to also upgrade sonar. Travis recently add the default java version to 11. See the keycloak repo with specific version 8 jdk configured in .travis.yml.

**Comment by mariorguezari** [comment]
Some subtle comments to consider when comitting comments:

**formatting and commented blocks in xml**
-> be careful when applying automatic format-source in the IDE (eclipse) affecting the whole file, especially in case of XML. The pom files default indentation is different than the default eclipse configuration for XML formating, so the diff will affect barely all the lines.
-> the block comments in xml are converted to one line comments, its orginal structure disappears. This happens in the pom file, line 352.

**commented blocks in the repository**
-> in general, commented out code (and blocks of code) are better managed by the repository history than leaving the commeted lines in the source files. This can lead to less readable code and mantaining residual lines between developers that doesn't know the original intent.

This is a minor thing, so the PR goes on.

**Comment by carloscaverobarca** [comment]
Perfect. I deleted the feature branch.

**Comment by carloscaverobarca** [comment]
Forgot to say that right now the changelog is automatically generated using the main description on the PR. We need to talk about this.

**Pull request merged**
