### PR TITLE
PostgreSQL support as persistence layer

### LINKED ISSUE #16: feature: Support PostgreSQL compliant with Apache 2.0 license
# Feature Request

**Describe the Feature Request**

Support PostgreSQL compliant with Apache 2.0. MySQL connector has a different commercial use and it cannot be used freely.

**Is your feature request related to a problem? Please describe**

Cover DB connectors compliant with Apache 2.0 would spread the use of the component.

**Describe Preferred Solution**

Add the PostgreSQL connector to the maven pom. Modify the configuration of the server and provide a docker-compose for testing.

### PR DESCRIPTION
**Pull request by carloscaverobarca**
## Proposed Changes

  - Add the dependencies to the maven pom
  - Configure the driver and hibernate if the DB_VENDOR env variable is POSTGRESQL
  - Modify the docker-compose and .env for testing

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests
- [x] Build locally
- [ ] Code format / lint
- [x] Docs have been reviewed and added

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Cover Derby, MySQL and MariaDB

Issue Number: #8 

Fixes #16 

## What is the new behavior?

- PostgreSQL can be configured as database with DB_VENDOR environment variable
- It can be tested using docker-compose

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Docker-compose has a lot of comments (mysql and mariadb containers for instance). I left them to ease the testing part of the different databases. I do not know if it is somewhat confusing.

### CODE REVIEW

**Comment by mariorguezari** [comment]
The README information is updated, which is great.
Looking at the files where the configuration for the databases affects, I suggest to extend a bit the description in the README with:
- the default deployment if you deploy the repository as it is
- the DB possibilities that can be configured with parameters in the environment variables and source code
  - the files that must be configured to use any of the other DB options: 
    - .env
    - docker-compose.yml

**Comment by mariorguezari** [comment]
About the .env file:
This file is crucial for the development, and as there are several configurable DB options, I suggest to keep the sample configuration of every DB_VENDOR in blocks, commented except the default one, instead of some commented and some uncommented, to facilitate changing from one to another.

For example:

```
# Database configuration 
# To be specified if keycloak reads DB_VENDOR in docker-compose.yaml
# MariaDB
# DB_VENDOR=MARIADB
# PostgreSQL
DB_VENDOR=POSTGRESQL
DB_ROOT_PASSWORD=root
DB_USER=fhir
DB_PASSWORD=fhir
DB_DB=fhirdb
# DB_HOST=mariadb
# DB_PORT=3306
DB_HOST=postgres
DB_PORT=5432
``` 

Could be:
```
# Database configuration 
# DB_VENDOR selects de DB estrategy. It must be coherent with docker-compose.yaml if you use docker deployment.
# DB_VENDOR= DERBY | MARIADB | POSTGRESQL | MYSQL
DB_VENDOR=POSTGRESQL

# In case DB_VENDOR is MARIADB
# DB_ROOT_PASSWORD=root
# DB_USER=fhir
# DB_PASSWORD=fhir
# DB_DB=fhirdb
# DB_HOST=mariadb
# DB_PORT=3306

# In case DB_VENDOR is PostgreSQL
DB_ROOT_PASSWORD=root
DB_USER=fhir
DB_PASSWORD=fhir
DB_DB=fhirdb
DB_HOST=postgres
DB_PORT=5432

# And the other DB options, in blocks
``` 

The default configuration should be named (if you look at the code, it is DERBY) and I think probably it should be also the default configuration in the .env file and docker-compose. What do you think?

**Comment by carloscaverobarca** [comment]
Totally agree with you. The default deployment should be Derby (the simplest one). Could you take care of this (configuration and documentation)?

**Comment by mariorguezari** [comment]
About the Java code, alles ist gut. 
Some small comments about FhirServerConfig class, DEFAULT_MYSQL_PORT acts as a DEFAULT_PORT, the naming could be confusing.

Asuming that the pom.xml has dependencies on all the possible databases is a side effect of having all the possibilities ready to change. Could it be a better solution to that? I'm thinking...

**Comment by mariorguezari** [comment]
All comments addressed! 
.env file has now a more healthy aspect :)
README also especifies the environment configuration.
Pull request accepted.

**Pull request merged**
